services:
  lifeos:
    build: .
    image: lifeos:latest
    container_name: lifeos
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./src/content:/app/src/content
    expose:
      - "4321"
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.lifeos.rule=Host(`lifeos.localhost`) || Host(`lifeos.wolfdivided`)"
      - "traefik.http.routers.lifeos.entrypoints=websecure"
      - "traefik.http.routers.lifeos.tls=true"
      - "traefik.http.services.lifeos.loadbalancer.server.port=4321"

networks:
  traefik_proxy:
    external: true
